name: example
description: "Open UI is a sandbox application that demonstrates the power of an Empathetech UI. If you like Open UI, checkout https://github.com/Empathetech-LLC/empathetech_flutter_ui"
version: 4.0.0+41
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter (Google)
  go_router: ^17.2.3
  intl: ^0.20.2
  shared_preferences: ^2.5.5

  # Community
  after_layout: ^1.2.0
  file_picker: ^12.0.0-beta.4
  file_saver: ^0.4.0
  line_icons: ^2.0.3
  provider: ^6.1.5+1
  window_manager: ^0.5.1
  xml: ^6.6.1

  # Empathetech
  empathetech_flutter_ui:
    path: ../
  efui_bios:
    path: ../../efui_bios

dev_dependencies:
  dependency_validator: ^5.0.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/app-icon.png

flutter_launcher_icons:
  image_path: assets/app-icon.png
  adaptive_icon_foreground: assets/app-icon.png
  adaptive_icon_background: "#FFA520DA"
  android: true
  ios: true
  background_color_ios: "#A520DA"
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "#A520DA"
  windows:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  color: "#A520DA"
  image: assets/app-icon.png
  android: true
  ios: true
  web: true
